version: 2.2.0.{build}
image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props;**\*.fsproj;**\*.xml'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild /restore /m /p:Configuration=Release /clp:v=m TaglibSharp.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: src\TaglibSharp\bin\Release
    type: zip

deploy:
  provider: NuGet
  api_key:
    secure: m49OJ7+Jdt9an3jPcTukHA==
  skip_symbols: false
  artifact: /.*\.nupkg/
